/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'pricing-data': PricingDatum;
    'comparison-articles': ComparisonArticle;
    'educational-guides': EducationalGuide;
    'review-articles': ReviewArticle;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'pricing-data': PricingDataSelect<false> | PricingDataSelect<true>;
    'comparison-articles': ComparisonArticlesSelect<false> | ComparisonArticlesSelect<true>;
    'educational-guides': EducationalGuidesSelect<false> | EducationalGuidesSelect<true>;
    'review-articles': ReviewArticlesSelect<false> | ReviewArticlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descriptive alt text, e.g. "StoveGuard Premium installed on a GE 5-burner gas stove" — not "stove image 2".
   */
  alt: string;
  /**
   * Optional caption shown beneath the image in article body.
   */
  caption?: string | null;
  /**
   * Optional attribution for third-party or embedded images.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Single source of truth for product pricing. Referenced by all content types. One update propagates everywhere on next build.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-data".
 */
export interface PricingDatum {
  id: number;
  /**
   * Display name, e.g. "StoveGuard", "Stove Shield".
   */
  brand: string;
  /**
   * URL-safe identifier. Auto-derived from brand if left empty.
   */
  brandSlug: string;
  /**
   * e.g. "StoveGuard Premium".
   */
  productName: string;
  productLine?: ('lite' | 'premium' | 'pro' | 'grip' | 'standard' | 'other') | null;
  /**
   * Price in US dollars. Decimals allowed (e.g. 29.99).
   */
  priceUsd: number;
  /**
   * US market only for v1. Schema kept extensible.
   */
  currency: 'USD';
  /**
   * Brand's official site URL. Tracking/affiliate query params are stripped automatically on save.
   */
  productUrl: string;
  specs?: {
    /**
     * Material thickness in millimeters.
     */
    thicknessMm?: number | null;
    materialType?: ('silicone' | 'fiberglass-coated-silicone' | 'aluminized-steel' | 'other') | null;
    /**
     * Maximum rated temperature in °F.
     */
    heatRatingFahrenheit?: number | null;
    warrantyMonths?: number | null;
    /**
     * Free-form, e.g. "28 x 20".
     */
    dimensionsInches?: string | null;
  };
  inStock: boolean;
  /**
   * Date this price was last manually verified against the official site.
   */
  lastVerifiedAt: string;
  /**
   * Internal editor note. Not displayed publicly.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Brand-vs-brand matchup articles. Prices in the comparison table are pulled live from linked pricing-data entries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison-articles".
 */
export interface ComparisonArticle {
  id: number;
  /**
   * e.g. "StoveGuard vs Stove Shield 2026: Tested Side-by-Side".
   */
  title: string;
  /**
   * URL path segment. Auto-derived as {brandA}-vs-{brandB} if left empty.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Set automatically when status flips to Published.
   */
  publishedAt?: string | null;
  readTimeMinutes?: number | null;
  /**
   * First brand in the matchup.
   */
  brandA: string;
  /**
   * Second brand in the matchup.
   */
  brandB: string;
  /**
   * SEO meta description — keep under ~160 characters.
   */
  metaDescription: string;
  /**
   * The TL;DR verdict box copy shown near the top of the article.
   */
  tldrVerdict: string;
  /**
   * Main article body — deep-dive sections.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The top spec table — one row per attribute (price, thickness, warranty, etc.).
   */
  comparisonRows?:
    | {
        label: string;
        valueA: string;
        valueB: string;
        /**
         * Citation URL for this row.
         */
        sourceUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The pricing-data entries whose live prices appear in this article. One price update propagates here on next build.
   */
  pricedProducts?: (number | PricingDatum)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Other comparison articles to link at the bottom.
   */
  relatedArticles?: (number | ComparisonArticle)[] | null;
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Informational, non-commercial guides (thickness, safety, how-to). No pricing or brand comparison — purely educational.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-guides".
 */
export interface EducationalGuide {
  id: number;
  /**
   * e.g. "Stove Protector Thickness Guide: How Thick Is Enough?".
   */
  title: string;
  /**
   * URL path segment. Auto-derived from title if left empty.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Set automatically when status flips to Published.
   */
  publishedAt?: string | null;
  readTimeMinutes?: number | null;
  /**
   * SEO meta description — keep under ~160 characters.
   */
  metaDescription: string;
  /**
   * The 40–60 word direct answer / key takeaway, shown in a callout box near the top of the guide.
   */
  keyTakeaway: string;
  /**
   * Main guide content.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Other educational guides to link at the bottom and in the sidebar.
   */
  relatedGuides?: (number | EducationalGuide)[] | null;
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Single-brand deep-dive reviews. The product-lineup table pulls live prices from linked pricing-data entries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-articles".
 */
export interface ReviewArticle {
  id: number;
  /**
   * e.g. "StoveGuard Review 2026: Honest Independent Breakdown".
   */
  title: string;
  /**
   * URL path segment. Auto-derived from brand if left empty.
   */
  slug: string;
  status: 'draft' | 'published';
  /**
   * Set automatically when status flips to Published.
   */
  publishedAt?: string | null;
  readTimeMinutes?: number | null;
  /**
   * Overall review score, 0–5.
   */
  ratingOutOf5: number;
  /**
   * The single brand under review.
   */
  brand: string;
  /**
   * SEO meta description — keep under ~160 characters.
   */
  metaDescription: string;
  /**
   * TL;DR verdict box copy — conclusion first (this is what AI Overviews pull).
   */
  verdict: string;
  /**
   * Main review body — company background, material breakdown, customer sentiment, first-hand review.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Honest positives — "What users love".
   */
  pros?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Honest negatives — "Common complaints".
   */
  cons?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The brand's product tiers shown in the lineup table. Prices pulled live from pricing-data on next build.
   */
  productLineup?: (number | PricingDatum)[] | null;
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Other brand reviews to link at the bottom and in the sidebar.
   */
  relatedReviews?: (number | ReviewArticle)[] | null;
  sources?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pricing-data';
        value: number | PricingDatum;
      } | null)
    | ({
        relationTo: 'comparison-articles';
        value: number | ComparisonArticle;
      } | null)
    | ({
        relationTo: 'educational-guides';
        value: number | EducationalGuide;
      } | null)
    | ({
        relationTo: 'review-articles';
        value: number | ReviewArticle;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-data_select".
 */
export interface PricingDataSelect<T extends boolean = true> {
  brand?: T;
  brandSlug?: T;
  productName?: T;
  productLine?: T;
  priceUsd?: T;
  currency?: T;
  productUrl?: T;
  specs?:
    | T
    | {
        thicknessMm?: T;
        materialType?: T;
        heatRatingFahrenheit?: T;
        warrantyMonths?: T;
        dimensionsInches?: T;
      };
  inStock?: T;
  lastVerifiedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison-articles_select".
 */
export interface ComparisonArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  readTimeMinutes?: T;
  brandA?: T;
  brandB?: T;
  metaDescription?: T;
  tldrVerdict?: T;
  body?: T;
  comparisonRows?:
    | T
    | {
        label?: T;
        valueA?: T;
        valueB?: T;
        sourceUrl?: T;
        id?: T;
      };
  pricedProducts?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedArticles?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educational-guides_select".
 */
export interface EducationalGuidesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  readTimeMinutes?: T;
  metaDescription?: T;
  keyTakeaway?: T;
  body?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedGuides?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-articles_select".
 */
export interface ReviewArticlesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  readTimeMinutes?: T;
  ratingOutOf5?: T;
  brand?: T;
  metaDescription?: T;
  verdict?: T;
  body?: T;
  pros?:
    | T
    | {
        point?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        point?: T;
        id?: T;
      };
  productLineup?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  relatedReviews?: T;
  sources?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}